#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Polkit agent
# /usr/lib/polkit-1/polkitd &

# Set wallpaper
swaybg --output '*' --mode fill --image ~/wallpapers/lake-nature.jpg &

# Apply themesg
~/.config/hypr/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &
